# Copyright (c) 2024-2026 Marcel <MarcelDevBr> and BRHealth Contributors.
# Licensed under the GNU Affero General Public License v3 (AGPLv3)
# or a commercial license agreement directly with the author.

"""
Type stubs para o pacote brhealth.
Fornece suporte a autocompletar e tipagem estática para VS Code, PyCharm, MyPy e Google Colab.
"""

from typing import Any, Dict, List, Optional, Tuple, Union

__version__: str

# Exceções Tipadas
class BRHealthError(Exception): ...
class SourceNotFoundError(BRHealthError): ...
class TransportError(BRHealthError): ...
class ValidationError(BRHealthError): ...

# Utilitário de Diagnóstico
def check_environment() -> Dict[str, bool]: ...

# Decodificadores Nativos
def read_dbc(path: str) -> RecordBatchWrapper: ...
def read_dbf(path: str) -> RecordBatchWrapper: ...
def decompress_dbc(input_path: str, output_path: Optional[str] = None) -> bytes: ...

# Harmonização Territorial IBGE
def calculate_ibge_dv(code_6_digits: Union[str, int]) -> int: ...
def harmonize_ibge_code(raw_code: Union[str, int]) -> str: ...
def validate_ibge_code(code: Union[str, int]) -> bool: ...
def reconcile_historical_ibge_code(raw_code: Union[str, int], reference_year: Optional[int] = None) -> str: ...

# Geoespacial Analítico (H3 & S2)
def latlng_to_h3(lat: f64, lng: f64, resolution: int) -> int: ...
def h3_to_latlng(h3_index: int) -> Tuple[float, float]: ...
def h3_index_to_coord(h3_index: int) -> Tuple[float, float]: ...
def h3_grid_disk(h3_index: int, k: int) -> List[int]: ...
def h3_grid_distance(origin: int, destination: int) -> int: ...
def latlng_to_s2(lat: float, lon: float, level: Optional[int] = None) -> int: ...
def coord_to_s2_cell(lat: float, lon: float, level: Optional[int] = None) -> int: ...
def s2_cell_to_coord(cell_id: int) -> Tuple[float, float]: ...

# Bioestatística e Mortalidade
def compute_apvp(ages: List[int], cutoff_age: Optional[int] = None) -> int: ...
def compute_apvp_rate(total_apvp: int, population: int) -> float: ...
def compute_batch_apvp(
    wrapper: RecordBatchWrapper,
    age_column: str,
    cutoff_age: Optional[int] = None,
    reference_population: Optional[int] = None,
) -> Dict[str, Any]: ...
def compute_age_standardized_mortality_rate(
    observed_deaths: List[int],
    local_pop: List[int],
) -> float: ...

# CSAP, Ontologias e Economia da Saúde
def classify_cid10(cid: str) -> Optional[int]: ...
def is_csap(cid: str) -> bool: ...
def csap_group_name(group_id: int) -> str: ...
def icd10_chapter(code: str) -> Dict[str, Any]: ...
def validate_biological_consistency(icd10: str, sex: str, age_years: int) -> bool: ...
def map_icd9_to_icd10(icd9: str) -> Optional[str]: ...
def map_icd10_to_icd9(icd10: str) -> Optional[str]: ...
def map_icd10_to_icd11(icd10: str) -> Optional[str]: ...
def map_icd10_to_snomed(icd10: str) -> Optional[str]: ...
def is_amputation_procedure(code: str) -> bool: ...
def is_dialysis_procedure(code: str) -> bool: ...
def parse_sigtap_code(code: str) -> Tuple[int, int, int, int, int]: ...
def lookup_atc(atc_code: str) -> Optional[str]: ...
def map_atc_to_rxnorm(atc_code: str) -> Optional[str]: ...
def compute_roi(avoidable_cost: float, investment: float, attributable_fraction: float) -> float: ...

# Ingestão Top-Level
def fetch(
    source_id: str,
    jurisdiction: Optional[str] = None,
    year: int = 2024,
    month: Optional[int] = None,
    harmonize_ibge: bool = True,
    assign_h3: Optional[int] = None,
    enrich_csap: bool = False,
    extra_filters: Optional[Dict[str, str]] = None,
) -> RecordBatchWrapper: ...

class RecordBatchWrapper:
    @property
    def num_rows(self) -> int: ...
    @property
    def num_columns(self) -> int: ...
    @property
    def shape(self) -> Tuple[int, int]: ...
    @property
    def columns(self) -> List[str]: ...
    @property
    def schema(self) -> Dict[str, str]: ...
    @property
    def manifest_json(self) -> Optional[str]: ...
    def column_names(self) -> List[str]: ...
    def head(self, n: Optional[int] = 5) -> RecordBatchWrapper: ...
    def tail(self, n: Optional[int] = 5) -> RecordBatchWrapper: ...
    def to_pandas(self) -> Any: ...
    def to_polars(self) -> Any: ...
    def to_pyarrow(self) -> Any: ...
    def to_dict(self) -> Dict[str, List[Any]]: ...
    def to_pydict(self) -> Dict[str, List[Any]]: ...
    def export_fair_manifest(self, path: str) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, key: Union[str, int, slice]) -> Any: ...

class HospitalMorbidityAccessor:
    def fetch(
        self,
        jurisdiction: Optional[str] = None,
        jurisdictions: Optional[List[str]] = None,
        year: Optional[int] = None,
        years: Optional[List[int]] = None,
        month: Optional[int] = None,
        harmonize_ibge: bool = True,
        assign_h3: Optional[int] = None,
        enrich_csap: bool = True,
    ) -> RecordBatchWrapper: ...

class VitalStatisticsAccessor:
    def fetch(
        self,
        source: str = "SIM",
        jurisdiction: Optional[str] = None,
        year: int = 2022,
        harmonize_ibge: bool = True,
        assign_h3: Optional[int] = None,
    ) -> RecordBatchWrapper: ...

class NotificationsAccessor:
    def fetch(
        self,
        disease: str,
        jurisdiction: Optional[str] = None,
        year: int = 2023,
        harmonize_ibge: bool = True,
        assign_h3: Optional[int] = None,
    ) -> RecordBatchWrapper: ...

class GlobalClimateAccessor:
    def fetch(
        self,
        source: str = "copernicus_era5",
        year: int = 2023,
        month: Optional[int] = None,
    ) -> RecordBatchWrapper: ...

class DemographicsAccessor:
    def fetch(
        self,
        source: str = "censo",
        jurisdiction: Optional[str] = None,
        year: int = 2022,
    ) -> RecordBatchWrapper: ...

class AmbulatoryAccessor:
    def fetch(
        self,
        jurisdiction: Optional[str] = None,
        year: int = 2023,
        month: Optional[int] = None,
        harmonize_ibge: bool = True,
    ) -> RecordBatchWrapper: ...

class EnvironmentalAccessor:
    def fetch(
        self,
        source: str = "inmet",
        jurisdiction: Optional[str] = None,
        year: int = 2023,
        month: Optional[int] = None,
    ) -> RecordBatchWrapper: ...

class SocialAccessor:
    def fetch(
        self,
        jurisdiction: Optional[str] = None,
        year: int = 2023,
        month: Optional[int] = None,
    ) -> RecordBatchWrapper: ...

class Engine:
    def __init__(self) -> None: ...
    def version(self) -> str: ...
    def source_count(self) -> int: ...
    def list_sources(self) -> List[str]: ...
    def validate_biological_consistency(self, icd10: str, sex: str, age_years: int) -> bool: ...
    def fetch(
        self,
        source_id: str,
        jurisdiction: Optional[str] = None,
        year: int = 2024,
        month: Optional[int] = None,
        harmonize_ibge: bool = True,
        assign_h3: Optional[int] = None,
        enrich_csap: bool = False,
        extra_filters: Optional[Dict[str, str]] = None,
    ) -> RecordBatchWrapper: ...
    @property
    def hospital_morbidity(self) -> HospitalMorbidityAccessor: ...
    @property
    def vital_statistics(self) -> VitalStatisticsAccessor: ...
    @property
    def notifications(self) -> NotificationsAccessor: ...
    @property
    def global_climate(self) -> GlobalClimateAccessor: ...
    @property
    def demographics(self) -> DemographicsAccessor: ...
    @property
    def ambulatory(self) -> AmbulatoryAccessor: ...
    @property
    def environmental(self) -> EnvironmentalAccessor: ...
    @property
    def social(self) -> SocialAccessor: ...
    @property
    def cache(self) -> CacheManager: ...

class CacheManager:
    def clear(self, source_id: Optional[str] = None) -> int: ...
    def clear_older_than(self, days: Optional[int] = None, cutoff_date: Optional[str] = None) -> int: ...
    def status(self, source_id: Optional[str] = None) -> Dict[str, Any]: ...
